// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3b__qktvVMiuPunavw3_AZZYKwApXP5g',
    appId: '1:229018527318:web:76b8188c5a4138bd233df7',
    messagingSenderId: '229018527318',
    projectId: 'qchat-129c3',
    authDomain: 'qchat-129c3.firebaseapp.com',
    storageBucket: 'qchat-129c3.appspot.com',
    measurementId: 'G-RLLY9J6J81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhjGArJvOc7hTOhqSEtkZ4vh6rGLH-J6I',
    appId: '1:229018527318:android:3192aa468d2b817e233df7',
    messagingSenderId: '229018527318',
    projectId: 'qchat-129c3',
    storageBucket: 'qchat-129c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9NxoFU23eIHrsvrqGAq9hT5Baw6Phgpc',
    appId: '1:229018527318:ios:5139e9b1076ce7c5233df7',
    messagingSenderId: '229018527318',
    projectId: 'qchat-129c3',
    storageBucket: 'qchat-129c3.appspot.com',
    iosBundleId: 'com.example.qChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9NxoFU23eIHrsvrqGAq9hT5Baw6Phgpc',
    appId: '1:229018527318:ios:234d8a1233324559233df7',
    messagingSenderId: '229018527318',
    projectId: 'qchat-129c3',
    storageBucket: 'qchat-129c3.appspot.com',
    iosBundleId: 'com.example.qChat.RunnerTests',
  );
}
